title: Liangtian He's Homepage
page-top-title: Liangtian He's Homepage
top-section-bg-text: Imaging Science and Scientific Computing
home-subtitle: Liangtian He (何亮田)
copyright-text: '&copy; Liangtian He 2024-2026. All Rights Reserved.'
