title: Liangtian He's Homepage
page-top-title: Liangtian He
top-section-bg-text: Imaging Science and Scientific Computing
home-subtitle: Liangtian He&ensp;|&ensp;何亮田
copyright-text: '&copy; Liangtian He 2023-2025. All Rights Reserved.'
